version: '3'

services:

  consul:
    image: consul:1.9.5
    container_name: consul-server
    ports:
      - "8500:8500"    # Porta da interface web do Consul
      - "8600:8600/udp" # DNS Service Discovery
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    networks:
      - dj-marcel

  frontdj:
    build: ./frontDj
    ports:
      - "3004:3004"
    command: npm start
    networks:
      - dj-marcel
    environment:
      - CONSUL_HTTP_ADDR=consul-server:8500
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3004 || exit 1"]
      interval: 30s
      retries: 3
      start_period: 5s
    labels:
      - "com.consul.register=true"

  api-client:
    build: ./djBackClient
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - dj-marcel
    environment:
      - CONSUL_HTTP_ADDR=consul-server:8500
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      retries: 3
      start_period: 5s
    labels:
      - "com.consul.register=true"

  api-playlist:
    build: ./djBackPlaylist
    ports:
      - "3001:3001"
    command: npm start
    networks:
      - dj-marcel
    environment:
      - CONSUL_HTTP_ADDR=consul-server:8500
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]
      interval: 30s
      retries: 3
      start_period: 5s
    labels:
      - "com.consul.register=true"

  api-reservation:
    build: ./djBackReservation
    ports:
      - "3002:3002"
    command: npm start
    networks:
      - dj-marcel
    environment:
      - CONSUL_HTTP_ADDR=consul-server:8500
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002 || exit 1"]
      interval: 30s
      retries: 3
      start_period: 5s
    labels:
      - "com.consul.register=true"

networks:
  dj-marcel:
    driver: bridge
